/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game_Canvas;

import Database.DBCaller;
import Database.PlayerRepository;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Michael Kevin Uy
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
        this.setSize(700,700);
        GameLogo.setIcon(scaleImage("NarutoLogo", GameLogo));
        btnOneP.setIcon(scaleImage("1PButton", btnOneP));
        btnTwoP.setIcon(scaleImage("2PButton", btnTwoP));
        GameLogo2.setIcon(scaleImage("KongLogo", GameLogo2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        bgPanel = new javax.swing.JPanel();
        GameLogo = new javax.swing.JLabel();
        btnOneP = new javax.swing.JButton();
        btnTwoP = new javax.swing.JButton();
        GameLogo2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(0, 204, 153));

        btnOneP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOnePMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOnePMouseExited(evt);
            }
        });
        btnOneP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnePActionPerformed(evt);
            }
        });

        btnTwoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTwoPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTwoPMouseExited(evt);
            }
        });
        btnTwoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOneP, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTwoP, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GameLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GameLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(GameLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GameLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnOneP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTwoP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTwoPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTwoPMouseExited
        // TODO add your handling code here:
        btnTwoP.setSize(btnOneP.getWidth()-10, btnTwoP.getHeight()-10);
        btnTwoP.setIcon(scaleImage("2PButton", btnTwoP));
    }//GEN-LAST:event_btnTwoPMouseExited

    private void btnTwoPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTwoPMouseEntered
        // TODO add your handling code here:
        btnTwoP.setSize(btnTwoP.getWidth()+10, btnTwoP.getHeight()+10);
        btnTwoP.setIcon(scaleImage("2PButton", btnTwoP));
    }//GEN-LAST:event_btnTwoPMouseEntered

    private void btnOnePMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnePMouseExited
        // TODO add your handling code here:
        btnOneP.setSize(btnOneP.getWidth()-10, btnOneP.getHeight()-10);
        btnOneP.setIcon(scaleImage("1PButton", btnOneP));
    }//GEN-LAST:event_btnOnePMouseExited

    private void btnOnePMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnePMouseEntered
        // TODO add your handling code here:
        btnOneP.setSize(btnOneP.getWidth()+10, btnOneP.getHeight()+10);
        btnOneP.setIcon(scaleImage("1PButton", btnOneP));
    }//GEN-LAST:event_btnOnePMouseEntered

    private void btnOnePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnePActionPerformed
        try {
            this.dispose();
            new DBCaller().deletePlayerDB(new PlayerRepository());
            new Game_Frame(1).setVisible(true);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOnePActionPerformed

    private void btnTwoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoPActionPerformed
        try {
            this.dispose();
            new Game_Frame(2).setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTwoPActionPerformed
        
    ImageIcon scaleImage(String fileName, JButton btn){
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("Images/" + fileName + ".png"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        Image dimg = img.getScaledInstance(btn.getWidth(), btn.getHeight(),
        Image.SCALE_SMOOTH);

        ImageIcon imageIcon = new ImageIcon(dimg);

        return imageIcon;
    }
    
    ImageIcon scaleImage(String fileName, JLabel lbl){
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("Images/" + fileName + ".png"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        Image dimg = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(),
        Image.SCALE_SMOOTH);

        ImageIcon imageIcon = new ImageIcon(dimg);

        return imageIcon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameLogo;
    private javax.swing.JLabel GameLogo2;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btnOneP;
    private javax.swing.JButton btnTwoP;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
